daktary:
  home: /multibao/modele_de_depot/readme.md
  meta:
    title: 'nom de mon dépôt'
    description: 'description de mon dépôt'

prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Auteurs"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Titre de la fiche"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          help: "en une courte phrase"
          value: ""

